### ISSUE TITLE
Breadcrumb : missing section part when coming back to course

### ISSUE THREAD

**Issue by matcho** [davidherney/moodle-format_onetopic#10]
Hi,

When navigating among a course sections, the breadcrumb is updated to reflect the navigation - it displays the current section as last element.

![moodle_bug_breadcrumb_expected](https://cloud.githubusercontent.com/assets/2674752/14142771/e0a466cc-f687-11e5-96ae-9131240e7545.png)

If you go out of the course (by going to Moodle's main page for example) then click on a link pointing to the course (on main page or in dashboard for example), it (Moodle ? The course format ?) remembers the section you were in and takes you back to it.

But, the breadcrumb only shows the course as last element, and the section part is missing. 

![moodle_bug_breadcrumb_problem](https://cloud.githubusercontent.com/assets/2674752/14142770/e0a44bf6-f687-11e5-9322-36869935d2f9.png)

Navigating in the course (changing section or activity for ex.) restores the normal behaviour.

As it also affects the block_course_contents plugin, I guess the Navigation system is to blame rather than the breadcrumb rendering.

Thanks,
Mathias

**Comment by davidherney** [comment]
Ready!!! In version for moodle 3.1

**Comment by matcho** [comment]
Thank you !
