### ISSUE TITLE
change request: rename asynchronous edit actions

### ISSUE THREAD

**Issue by lassnj** [davidherney/moodle-format_onetopic#100]
Our users don't understand that "asynchronous edit actions" enables them to move resources between tabs. Please rename it to "Move resources between tabs" and the corresponding link to "Enable".

Thank you so much!

**Comment by davidherney** [comment]
Hi @lassnj ...

You can change the text in the language customization into moodle administration.

Saludos

**Comment by lassnj** [comment]
Hi David,
thanks for the reply. I know that I can change the text. I wanted to add the improvement for all users and tried to change it in the German Amos Moodle Translation, there I got the reply that it should be consistent across languages although the reviewer agreed with the improved wording, the translation had to be rejected. That's why I opened the ticket here.

I will change it our local installation, just tried to give back.
Thanks anyways!
Regards
Julia

**Comment by rschrenk** [comment]
I agree that this would be an improvement!

**Comment by rschrenk** [comment]
Hello @davidherney 

I just want to ask - are there any news regarding this issue?

Kind regards

**Comment by rschrenk** [comment]
@lassnj 
kannst du deine Vorschläge bei AMOS eintragen? 
https://lang.moodle.org/local/amos/view.php?v=31000&t=1637680230&l=de&c=format_onetopic

**Comment by wildgirl** [comment]
I'm also in agreement with Julia that "Move resources between tabs" is easier to understand. It is now changed in the English US language pack.
