### ISSUE TITLE
Chrome menu scroll issue.

### ISSUE THREAD

**Issue by miropaananen** [davidherney/moodle-format_onetopic#101]
On moodle 3.9 When clicking on the menubars link/tab the browser scrolls down to the content. On chrome we noticed it scrolls down too much and it hides the top menu bar.  We don't have this issue on Firefox. Could this issue be fixed so that on chrome it would not hide the menu when it scrolls down to the content.

Screenshot of boost theme using chrome browser after clinking on topic 1

![image](https://user-images.githubusercontent.com/47216899/117977979-0814fb80-b33a-11eb-84d0-fc96066e6203.png)

Screenshot of boost theme using firefox browser after clinking on topic 1

![image](https://user-images.githubusercontent.com/47216899/117978426-86719d80-b33a-11eb-8be2-e11f3f255e9a.png)

I think the issue is that the scroll doesn't adjust to the height of the navigation bar. Could this issue be fixed so that it takes on account the height of the navbar automatically or that you could specify the height of the navbar trough the formats general settings?

**Comment by davidherney** [comment]
Hi @miropaananen ...

I implemented this change in the last release (master branch), please test.

Saludos

**Comment by miropaananen** [comment]
I tested it and it doesn't have the same issue now. Thank you so mutch!
