### ISSUE TITLE
Icons for marker and sub tabs

### ISSUE THREAD

**Issue by sarahjcotton** [davidherney/moodle-format_onetopic#102]
This isn't an issue but something I implemented via our theme renderer... we've had some really positive feedback so thought I'd share it back. I'm sure there's probably a better 'Moodle' way of doing it but you get the gist. Thanks for a great plugin!

Add level class to child tabs:
https://github.com/ltu-solent/moodle-theme_solent/blob/7a5b7f81be759e4dbd18b0baba1e09795d646969/classes/output/format_onetopic_renderer.php#L162

Add font-awesome icon to marker tab:
https://github.com/ltu-solent/moodle-theme_solent/blob/7a5b7f81be759e4dbd18b0baba1e09795d646969/classes/output/format_onetopic_renderer.php#L199

Add font-awesome icon to parent tabs:
https://github.com/ltu-solent/moodle-theme_solent/blob/7a5b7f81be759e4dbd18b0baba1e09795d646969/classes/output/format_onetopic_renderer.php#L218

We've styled our tabs slightly differently though:
<img width="605" alt="Capture" src="https://user-images.githubusercontent.com/2684004/119850490-80b4b400-bf05-11eb-9725-2703bb165a6b.PNG">

**Comment by davidherney** [comment]
Hi @sarahjcotton ...

It was included in new release for Moodle 4.x

Gracias

Saludos
