### ISSUE TITLE
Request: Please add git tags for the released versions to the repository

### ISSUE THREAD

**Issue by danowar2k** [davidherney/moodle-format_onetopic#103]
Our deployment mainly uses the git repository. So we would greatly appreciate it if you added git release tags for your versions you released on https://moodle.org/plugins.

To make it as easy as possible here are the commands that should create the appropriate release tags:

```
# add tag for la almeria (2020122701) (https://moodle.org/plugins/format_onetopic/la-almeria/23393)
git tag -a "la almeria (2020122701)" 9df2e8592a1a94a30da49f0b2bf6eb2b29f5cb6c -m "ADDITIONAL OPTIONAL INFO"
# add tag for san juan (2018010608) (https://moodle.org/plugins/format_onetopic/san-juan/20808)
git tag -a "san juan (2018010608)" bb31fad6d5823a1bb065c9756cf3efa11ca8317c -m "ADDITIONAL OPTIONAL INFO"
```

**Comment by davidherney** [comment]
Hi @danowar2k...

Please propose other tag name, this name is not valid:

```
$> git tag -a "san juan (2018010608)" bb31fad6d5823a1bb065c9756cf3efa11ca8317c -m "ADDITIONAL OPTIONAL INFO"
fatal: 'san juan (2018010608)' no es un nombre de tag válido.
```

Saludos

**Comment by danowar2k** [comment]
git tag -a "san_juan_(2018010608)" bb31fad6d5823a1bb065c9756cf3efa11ca8317c -m "ADDITIONAL OPTIONAL INFO"

git tag -a "2018010608" bb31fad6d5823a1bb065c9756cf3efa11ca8317c -m "ADDITIONAL OPTIONAL INFO"

git tag -a "1.2.0" bb31fad6d5823a1bb065c9756cf3efa11ca8317c -m "ADDITIONAL OPTIONAL INFO"
That last one was just guessing. I personally prefer semantic versioning (https://semver.org/lang/de/). But I don't know what release numbers your releases would correspond to, as names like "san juan" tell me nothing at all.
You'd have to go from your first release as 1.0.0 and go from there, what you changed etc.

git tag -a "MOODLE_MAJOR_MINOR-1.2.0" bb31fad6d5823a1bb065c9756cf3efa11ca8317c -m "ADDITIONAL OPTIONAL INFO"

Another possibility, if your releases correspond to Moodle minor releases mostly. So you could have 3.5-1.2.0 and 3.9-1.2.0, which would basically have the same functionality but adapted to Moodle API changes.

**Comment by davidherney** [comment]
Hi @danowar2k ...

You have the reason. I changed the release name. 
Now the release name have: 
- The two first numbers according with the moodle version
- The last number is the Onetopic current release 00 - 99
- My "special name" is into brackets

Something like: '3.11.04(la almeria)'

Better?

Saludos

**Comment by danowar2k** [comment]
I like the new naming scheme more than the non-descriptive one before, yes :-)

https://github.com/davidherney/moodle-format_onetopic/tags There are no git tags yet here, which what the original request was about. Will you add any of those to github, too? (I saw that you released 3.11.04(la almeria)) on moodle.org)

**Comment by davidherney** [comment]
Tags/release added... please check.

Saludos

**Comment by danowar2k** [comment]
I like the tags and their scheme. The only thing that comes to mind is: 

If you use "The last number is the Onetopic current release 00 - 99", shouldn't `v4.1.2` be `v4.1.02` ?

**Comment by davidherney** [comment]
Yes... it was an error. Changed!

**Comment by danowar2k** [comment]
I rather like `v4.1.02` better than `v4.01.02`, though. The Moodle major.minor releases don't have the leading zeros, so you shouldn't need those, either.

About your "release number", will that be the release number during a Moodle minor (meaning, will there be v4.2.01, v4.2.02, v4.2.03 etc. and then again v4.3.01, v4.3.02 ...) or will that be continuous releases (as in v4.2.06 ... v.4.2.07 .... v4.3.07 ... v4.3.08)

If you know what I mean?

**Comment by danowar2k** [comment]
By the way, you can always delete unwanted tags again using
```
git tag -d TAGNAME; git push --delete origin TAGNAME
```

**Comment by danowar2k** [comment]
Anyway, I'm ok with the current tags, you can close this one now :-)
