### ISSUE TITLE
Cannot add activities to a course with more than 52 sections

### ISSUE THREAD

**Issue by anieminen** [davidherney/moodle-format_onetopic#108]
Hi,

If a course using Onetopic format has more than 52 sections, you cannot create new activities to the last sections. This happens because section count exceeds the default maximum number of sections (52), which apparently comes from the old "weekly" course format.

![error_sections](https://user-images.githubusercontent.com/15781654/140485419-5c1048fc-4d11-4a32-a4db-69acb7e48225.PNG)

In Moodle 3.9.4 a new validation was added for the "section" parameter when adding a new activity. This can cause problems with course formats that don't define their own maximum number of sections: https://docs.moodle.org/dev/Moodle_3.9.4_release_notes#Warning_-_courses_with_many_sections

**Comment by Urpokarhu1** [comment]
@davidherney

**Comment by anieminen** [comment]
It seems that there is a workaround: Go to Site administration > Courses > Course default settings. Change the "Maximum number of sections" value to a bigger number, that exceeds the count of sections on the course, where the error was thrown.

**Comment by davidherney** [comment]
Yes... Onetopic use the default moodle max section configuration.

Saludos
