### ISSUE TITLE
Moodle 3.11 deprecation: \core_course_renderer::course_section_cm_completion()

### ISSUE THREAD

**Issue by danowar2k** [davidherney/moodle-format_onetopic#112]
See https://github.com/moodle/moodle/blob/master/course/upgrade.txt#L73.

Used here: https://github.com/davidherney/moodle-format_onetopic/blob/d4e4cafe0a3c25a39473d3716fb108b27da9ea88/renderer.php#L865

**Comment by davidherney** [comment]
Thx @danowar2k...

Deprecated method changed in MOODLE_311_stabilization branch. Waiting for bot validations in order to integrate.

Saludos
