### ISSUE TITLE
sectionactionnotsupported

### ISSUE THREAD

**Issue by PhilipWaage** [davidherney/moodle-format_onetopic#116]
Since updating to Moodle 4.0, I can no longer delete sections in the one-topic format. The following message appears: 
**sectionactionnotsupported**
Has anyone already had experience with this problem and  a corresponding solution suggestion?

**Comment by carlessanz** [comment]
Same problem Philip. Does anyone have a solution to this problem?

**Comment by sh-csg** [comment]
This is fixed by PR #117

**Comment by gvanbo** [comment]
Quick question, will OneTopic be supported in Moodle 4.0 and beyond?

**Comment by davidherney** [comment]
The compatibility is ready... now, I need testers. I await your comments.
