### ISSUE TITLE
4.0+ beta: Vertical alignment of tabs not working

### ISSUE THREAD

**Issue by PhMemmel** [davidherney/moodle-format_onetopic#120]
Using the latest `MOODLE_40_compatibility` branch on latest moodle `master` vertical alignment of tabs is not working: They are still aligned horizontally despite selecting `vertically` in the course format options section of the course settings.

However, tabs on the second level are aligned vertically.

**Comment by davidherney** [comment]
You're right. I made a mistake that I just corrected.

Gracias @PhMemmel
