### ISSUE TITLE
4.0+ beta: Updating section bar on changing sections

### ISSUE THREAD

**Issue by PhMemmel** [davidherney/moodle-format_onetopic#121]
@davidherney In the "coming soon" section you wrote that the section bar is not updating when removing a section and that this feature will come soon.

I just wanted to add that this rebuild of the sections bar also has to be triggered when moving sections around with the course index.

Thx for all the work!

**Comment by davidherney** [comment]
You're right. I changed the README a bit.

Gracias @PhMemmel
