### ISSUE TITLE
No onetopic/format.js file

### ISSUE THREAD

**Issue by sarahjcotton** [davidherney/moodle-format_onetopic#13]
The version for Moodle 3.0 (2016020501) now has 

`$PAGE->requires->js('/course/format/onetopic/format.js');`

on line 100 however format.js  does not appear to be included in this branch and throws error:

"Coding error detected, it must be fixed by a programmer: Attempt to require a JavaScript file that does not exist."

`Debug info: /course/format/onetopic/format.js`
`Error code: codingerror`
`Stack trace:`
`line 699 of \lib\outputrequirementslib.php: coding_exception thrown`
`line 422 of \lib\outputrequirementslib.php: call to page_requirements_manager->js_fix_url()`
`line 100 of \course\format\onetopic\format.php: call to page_requirements_manager->js()`
`line 280 of \course\view.php: call to require()`

**Comment by davidherney** [comment]
Added the format.js file

Saludos

**Comment by sarahjcotton** [comment]
Many thanks!

**Comment by aspark21** [comment]
While this is resolved in master & MOODLE_31 branches, this has not been resolved in the MOODLE_30 branch. Any chance it could be please?

**Comment by davidherney** [comment]
Ready!!!

Resolved in the MOODLE_30

**Comment by aspark21** [comment]
Yay!! 

Thanks you very muchly!
