### ISSUE TITLE
Accessibility: Allow admins to disable tab styling

### ISSUE THREAD

**Issue by sharpchi** [davidherney/moodle-format_onetopic#132]
For accessibility reasons (i.e. a staggeringly poor choice of colour combinations) we remove the settings that allows teachers to change tab colours. So I'm going to do a pull request that makes those settings optional for the site administrator to turn on or off.

**Comment by davidherney** [comment]
Hi @sharpchi ...

Interesting... added in 2022081606 release for Moodle 4.0/4.1.

Saludos

**Comment by ralf-krause** [comment]
From the same reason it would be a good idea to set some css for all onetopic courses. I like to set `font-weight: bold; font-size: 1.2em;` for all onetopic courses. 

Yes, it‘s possible to do the in the theme scss but it should be a global course format setting. currently I use the Boost scss to format the tabs in the onetopic courses. `.format_onetopic-tabs { font-weight: bold; font-size: 1.2em; }`
