### ISSUE TITLE
Change section order

### ISSUE THREAD

**Issue by frumbert** [davidherney/moodle-format_onetopic#133]
On Moodle 3.11, how do you change the section order? (Boost / Classic). There are no "move section up/down" links, dragging tabs doesn't work. There is nothing to indicate or change the order on the edit screen. Has this just been overlooked?

I currently have to turn off one topic, change the order from a different course format, then turn one topic back on.

**Comment by james-cnz** [comment]
For Moodle 3.x, with edit mode on, in any section other than 0, if you scroll to the bottom of the page, there's "Tabs edition utilities", and when that's expanded, "Move current topic".  Click the topic you want the current topic moved over.  i.e. if you click a topic before the current one, the current topic is moved over it to be before it, whereas if you click a topic after the current one, the current topic is moved over it to be after it.  (In Moodle 4.0 with the Boost theme, you can drag and drop in the course index on the left side of the page.)
