### ISSUE TITLE
PHP 8 throws an exception on uncountable object

### ISSUE THREAD

**Issue by sharpchi** [davidherney/moodle-format_onetopic#141]
I was creating a course via the Moodle webservice, which sets the course format to onetopic.
When I visited the page I got the error displayed in the screenshot below.
Looking at the code, it appears it's at least possible for $secondtabslist->tabs to be unset.
Perhaps $tabstree should be initialised with an empty array on $tabstree->tabs.
https://github.com/davidherney/moodle-format_onetopic/blob/3178c4773125aee92ae7b6ff3d1e22d186eb4bde/classes/tabs.php#L127

![tabscount2](https://user-images.githubusercontent.com/3774280/214629966-2529fbf2-5d43-4b32-bc2d-9d2066d4866b.png)

**Comment by davidherney** [comment]
Thanks... it was fixed yet.

Saludos
