### ISSUE TITLE
Duplication of activitiy in section 0

### ISSUE THREAD

**Issue by cre-eledia** [davidherney/moodle-format_onetopic#154]
If you have _Visualization mode of section 0_  set to "Before the tabs" the activity of section 0 gets displayed twice (before the tabs), iff all other topics are hidden and you are logged in as student.

**Comment by izendegi** [comment]
Hi,

We've also suffered this issue on Moodle 4.2 with the latest version of the plugin, and have reproduced it also on Moodle 4.3 and 4.4.

As @cre-eledia says, it happens when the 0 section is set to show "Before the tabs", and after changing it to show "As tab" doesn't happen.

**Comment by davidherney** [comment]
Fixed in the last release.

Saludos

**Comment by izendegi** [comment]
Thank you, @davidherney !

**Comment by cre-eledia** [comment]
Very appreciated @davidherney!
