### ISSUE TITLE
Bulk editing in Moodle 4.2 does not work in format_onetopic 

### ISSUE THREAD

**Issue by rschwarzinger** [davidherney/moodle-format_onetopic#159]
does work in format_topics:
![image](https://github.com/davidherney/moodle-format_onetopic/assets/76841651/f9c9e149-d8b3-48e3-b6e9-402c0d76f7a4)

does not work in format_onetopic
![image](https://github.com/davidherney/moodle-format_onetopic/assets/76841651/80861792-3857-4de8-b2cb-fbc2087e1708)

Tools for deleting, ... are missing.

**Comment by izendegi** [comment]
Hi @rschwarzinger,

I've seen that there is the pull request #149 adds the code needed to support this new feature.

**Comment by davidherney** [comment]
Hi @rschwarzinger ...

Fixed in the latest release.

Saludos
