### ISSUE TITLE
Use different/additional css rules to mark active tab

### ISSUE THREAD

**Issue by PhMemmel** [davidherney/moodle-format_onetopic#161]
The ability to change the CSS of a certain tab is a greatly appreciated feature of this course format. One of the most frequently use case is changing the colors of the tabs.

However, when changing the background color, there is no way for the user to tell anymore which tab is the currently active one, because the css rule for marking the currently active tab does not apply anymore (inline style is more specific).

I suggest to replace or amend the usage of the background-color with a different css rule instead/in addition to the background-color, for example a box-shadow, adding icons with before pseudoselector or anything else.

**Comment by MSMCDigitalLearning** [comment]
Additional note about the active tabs:
We just upgraded to Moodle 4.1. The Onetopic format still brings users back to their previous tab when they exit and re-enter a course site. However, on re-entry the Topic 0 tab is highlighted by default. Perhaps related to this issue?

![image](https://github.com/davidherney/moodle-format_onetopic/assets/158207046/00869922-6aba-4c76-afe6-0e49657d7b43)

**Comment by sh-csg** [comment]
Failing GHA is not related to this PR

**Comment by davidherney** [comment]
Hi...

Please, on future occasions report issues in different tickets when they are different.

@PhMemmel I have prioritized site level tab styles when they are: active, highlighted or disabled. For this it is necessary to use the tab designer in the site administration.

@MSMCDigitalLearning I have fixed this case in the current release. Please try it.

Saludos

**Comment by MSMCDigitalLearning** [comment]
@davidherney Thanks! Could you confirm which version of the plugin has the fix? We are currently on Moodle 4.1 and our DevOps team didn't see anything in the release notes for 4.1.11(PiedrasTeherán) (2022081611).

If it's for the versions of Moodle 4.2 or onward, we'll look forward to it when we upgrade. :)

**Comment by davidherney** [comment]
From Branch MOODLE_403_STABLE (for Moodle 4.2+ and 4.3+)
