### ISSUE TITLE
Plugin formatting in the Space theme

### ISSUE THREAD

**Issue by rodrigoalinericnec** [davidherney/moodle-format_onetopic#183]
I noticed that the formatting of the plugin in the Space theme (in dark mode) looks strange.
![Captura de tela 2024-05-10 081919](https://github.com/davidherney/moodle-format_onetopic/assets/169453393/21b0d642-8a54-4696-ac90-8867e43479c8)

**Comment by davidherney** [comment]
Hi @rodrigoalinericnec....

Could you report it to the creator of the graphic theme? It is there where the necessary adjustments could be made.

Saludos
