### ISSUE TITLE
Module scope tabs not visible when entering SCORM Package

### ISSUE THREAD

**Issue by encodecreate** [davidherney/moodle-format_onetopic#184]
If a course contains a SCORM module, module scope tabs only appear on the SCORM package's entry page. Once a user clicks the "ENTER" link, the tabs are no longer shown.

![image](https://github.com/davidherney/moodle-format_onetopic/assets/110412239/14ebef84-1496-4d32-988d-d9d860b2bf58)

![image](https://github.com/davidherney/moodle-format_onetopic/assets/110412239/26258a86-7e97-4f4c-ae45-040fd47fe270)

**Comment by davidherney** [comment]
Included in version to Moodle 4.3 and 4.4
