### ISSUE TITLE
show Topic bar in actitvity

### ISSUE THREAD

**Issue by ltanh1906** [davidherney/moodle-format_onetopic#190]
The topic bar is not showing when i access an activity or resource of a topic. How i can show it ?

**Comment by davidherney** [comment]
Hi @ltanh1906 ...

Have you already enabled the "Default scope" parameter at the site level?

PD: Provides more information: moodle version, plugin version and others.

Saludos

**Comment by ltanh1906** [comment]
> Hi @ltanh1906 ...
> 
> Have you already enabled the "Default scope" parameter at the site level?
> 
> PD: Provides more information: moodle version, plugin version and others.
> 
> Saludos

. Im not enabled the "Default scope" yet. It working now. Tysm
