### ISSUE TITLE
Section 0 displayed twice

### ISSUE THREAD

**Issue by hanirok** [davidherney/moodle-format_onetopic#194]
Hi!

In Moodle version 4.1.10, when section 0 appears before the tabs and all tabs are hidden, the content of section 0 is displayed twice. This issue occurs with plugin version 4.1.04(PiedrasTeherán) and is resolved by displaying one of the tabs.

**Comment by davidherney** [comment]
Hi @hanirok ...

This has been fixed in more recent versions. You need to upgrade the plugin. For Moodle 4.1 the Onetopic version is 4.1.12

Saludos
