### ISSUE TITLE
Topic 0 is in italic, ability to change it?

### ISSUE THREAD

**Issue by Jarvil** [davidherney/moodle-format_onetopic#20]
Hello,

by default topic 0 is in italic like _Topic 0_ Can you make it optional so that we can have it without styling if we want? The same style that Topic 1, Topic 2 etc. has.

**Comment by davidherney** [comment]
Hi Jarvil...

the italic style is not for Topic 0, it style is assigned to the "current" section (Highlight). You can change it with some one:

1. Configure other topic like the active: "_Edit_" > "_Highlight_"
2. Set manually the style in "_Edit section_" > "_CSS properties_". Put: `font-style: normal;`
3. By sources, remove the next line in **course/format/onetopic/styles.css**
`.format-onetopic .tab_content.marker { font-style: italic; }`

Saludos
