### ISSUE TITLE
Tabs format section delete error

### ISSUE THREAD

**Issue by cybernotic** [davidherney/moodle-format_onetopic#25]
When in editing mode, if I delete a section 'Topic 5' for example, I will then be prompted to confirm the action, I click yes, I am then presented with the error displayed below - Moodle 3.1.4 and 3.1.5 has the same result.

![capture1](https://cloud.githubusercontent.com/assets/18535468/25387445/c71f4112-29c2-11e7-97fd-76591bca00ae.PNG)

If I click on continue it will send me to the home page, I will then have to logout and login again to not get that error message again when re-visiting the course, this occurs with any course new or old.
I wanted to find out if this error can be replicated and if the issue can be looked in to or it could just be an issue with our Moodle setup. Thanks for your time

**Comment by davidherney** [comment]
Fixed on master and MOODLE_31

**Comment by cybernotic** [comment]
Thank you very much for your quick response and time in looking in to this.

Regards
David
