### ISSUE TITLE
M32: Deletion of topic results in error

### ISSUE THREAD

**Issue by rlcharles** [davidherney/moodle-format_onetopic#30]
After deleting a topic, an error appears "This section does not exist"
Using Moodle 3.2, 

1. create a course with a onetopic format
2. Navigate to a topic
3. Turn on editing
4. Using the edit button select delete
5. Confirm deletion.

The result is a redirection to viewing the course with the section does not exist, to get around this error you need to logout and log back in.

**Comment by davidherney** [comment]
Hi rlcharles...

what Onetopic version you use? An equal error was fixed in the last release. Please check and comment me.

Saludos
