### ISSUE TITLE
Feature request: Display topic 0 in tab edition utilities

### ISSUE THREAD

**Issue by Jarvil** [davidherney/moodle-format_onetopic#31]
Hello,

In my opionin Topic 0 should be displayed in tab edition utilities because when you move child tabs and click topic 1 they are moved as child tabs under topic 0 but in the tabs editions utilities they show up as a main level/normal topics because topic 0 isn't displayed here. This can be very confusing for a normal user.

![topic1](https://user-images.githubusercontent.com/15193418/27723863-c72a486c-5d77-11e7-985a-d9b84205e8ec.PNG)

![topic2](https://user-images.githubusercontent.com/15193418/27723876-cbffeb44-5d77-11e7-9217-cdd2e9de1d47.PNG)

**Comment by davidherney** [comment]
It is solved in the new release #35 

Thanks
