### ISSUE TITLE
Moodle 3.3 stealth activities doesn't work

### ISSUE THREAD

**Issue by Jarvil** [davidherney/moodle-format_onetopic#33]
Hello,

I just noticed that Moodle 3.3 new feature stealth-activities doesn't work with onetopic. You can hide the activity but you don't have the option "make available" in the menu like with f.ex. topic activity.

https://docs.moodle.org/33/en/Stealth_activities

![onetopic1](https://user-images.githubusercontent.com/15193418/30951664-ddf7a354-a42c-11e7-82a8-e6e19da37389.png)

![onetopic2](https://user-images.githubusercontent.com/15193418/30951675-e6c65106-a42c-11e7-9d3b-f105a298f3e3.PNG)

![onetopic3](https://user-images.githubusercontent.com/15193418/30951687-f3b953ae-a42c-11e7-9d6f-d0b199411fbf.png)

**Comment by Jarvil** [comment]
Hello @davidherney

**Comment by Jarvil** [comment]
He @davidherney any progress on this?

**Comment by Jarvil** [comment]
Any progerss ont his @davidherney

**Comment by davidherney** [comment]
Ready!

It is solved in the new release #35

Thanks

**Comment by davidherney** [comment]
Please test!
