### ISSUE TITLE
Automatic display and opening of the current tab

### ISSUE THREAD

**Issue by Marcway1** [davidherney/moodle-format_onetopic#39]
Hello David and dear friends,

Please kindly ask me, in the following question:

1- Consider, that a particular course, has 10 weeks. In the One Topic plugin, there will be 10 items: Week 1, Week 2, Week 3, ..., Week 10.

2 - Currently in the version we use, when the student enters the Moodle, you will always see Week 1 open, even if the Course is in Week 2.

3 - Would it be possible to configure the Plugin One Topic so that as soon as week 2 starts, all students see Week 2 open automatically?

Thank you! Marcelo.

**Comment by davidherney** [comment]
Hi @Marcway1 

I added a new feature inspired in your proposal: Setted the marked section as the default section. However, you need mark the current section manually.

Please, test this and comment.

**Comment by Marcway1** [comment]
Hi David,

Thank you! I tested it here and it worked. The section has been marked.

Would it be possible to have another item inside the menu, which in addition to marking the section, would also be possible to configure it to open the marked section?

Example: We have 10 topics. Whenever students access Moodle, they see topic 1 open. When the course goes to week 2 (topic 2), students continue to see topic 1 when they enter Moodle, even with topic 2, marked by us.

Would it be possible, in addition to marking the section, to have the option that the topic marked be the topic the student sees? In this case, topic 2.

Thanks, David.

Saludos, Marcelo.

**Comment by davidherney** [comment]
Hi @Marcway1 ...

You test the last version? Because it is exactly the feature:
- The teacher mark a section
- The marked section is displayed to student when enters to the course

Please, test it.

Saludos

**Comment by Marcway1** [comment]
Hi David,

In Moodle 3.2.5+, I did not get the effect.

I installed Moodle 3.3 and it worked!

Thank you! It was excellent!

Saludos, Marcelo.
