### ISSUE TITLE
Moodle upgrade from 2.8 to 2.9 issue with section layouts

### ISSUE THREAD

**Issue by Jeremy-Meades** [davidherney/moodle-format_onetopic#4]
Hi
Springwood High School use OneTopicFormat and in Moodle 2.8 it has worked perfectly. They upgraded to Moodle 2.9 and the content within the whole course has moved and now appears as one list of content under one topic/section. Originally, the content was spread across 19 sections. I have attached an image which I hope helps. Please let me know if you need more information. All content is now in the Dance section.

![springwood-onetopicformat](https://cloud.githubusercontent.com/assets/12937892/8210045/19ac9672-1508-11e5-9370-9d1fb901abba.jpg)

Thanks

Jeremy

**Comment by davidherney** [comment]
Hi Jeremy...

I don't understand your problem.

If the problem is the tabs visualization: it occur because in some themes is added additional tags in the tabs renderization. I solved this problem with the next CSS line in the "Afterburner" theme:

```css
.format-onetopic .onetopic .tab_content { display: inline; background: none; }
```

About the topic list on bottom of the page, It is only visible in edition mode in order to improve the tabs edition actions.

I want that this solve your inquire, write me again with more detail if it not.

Saludos

**Comment by Jeremy-Meades** [comment]
Hi David
The course contains 19 topics/sections and each topic/section had content. After the upgrade from Moodle 2.8 to 2.9 all of the content is now contained in 1 topic/section. It looks like the content has moved from all the other topics/sections into 1 topic/section.

Thanks for the CSS tip.

Jeremy

**Comment by davidherney** [comment]
Hi...

check if in other format you can see the resources normally, because this does not seem of the course format, maybe is a bug in the platform update process. The course format does not change the resources.

Saludos

**Comment by Jeremy-Meades** [comment]
Hi
The school have changed to a different theme but the display issue persists. I've tried using CSS to resolve the CSS but that does not work.

Not sure what next steps to take other than rolling back the upgrade. Ideas?

**Comment by davidherney** [comment]
"rolling back the upgrade" between versions is not possible. However, the course format does not change the resources. Did you check with another course format? Does persist the problem?

Saludos

**Comment by Jeremy-Meades** [comment]
Hi David
Yes, we checked other course formats and the resources/activities remain in the one topic section.
We will rollback the Moodle upgrade to 2.8. That will put the school back to where they were and we will find out why the resources/activities moved during the Moodle upgrade process. I can find no other reports of this happening in other Moodle sites so I am beginning to think that there may have been some user intervention.

Many thanks for your time and please close this ticket.
