### ISSUE TITLE
error when duplicating last topic/section

### ISSUE THREAD

**Issue by whymiss** [davidherney/moodle-format_onetopic#40]
In San Juan we are getting errors when duplicating the last section/topic. Its fine for all other sections but if there is on last section it errors as follows in Moodle 3.3.4+
Debug info: SELECT * FROM {course} WHERE id IS NULL
[array (
)]
Error code: invalidrecord
Stack trace: 
•	line 1533 of /lib/dml/moodle_database.php: dml_missing_record_exception thrown
•	line 1509 of /lib/dml/moodle_database.php: call to moodle_database->get_record_select()
•	line 588 of /lib/datalib.php: call to moodle_database->get_record()
•	line 443 of /lib/modinfolib.php: call to get_course()
•	line 412 of /lib/modinfolib.php: call to course_modinfo->__construct()
•	line 2095 of /lib/modinfolib.php: call to course_modinfo::instance()
•	line 896 of /course/lib.php: call to get_fast_modinfo()
•	line 939 of /course/lib.php: call to course_create_sections_if_missing()
•	line 1882 of /course/lib.php: call to course_add_cm_to_section()
•	line 132 of /course/format/onetopic/duplicate.php: call to moveto_module()
Regards,
Yvonne

**Comment by davidherney** [comment]
Hi @whymiss ...
Thanks by the issue report. I fix it in the last release (#42).

Please, test this and comment in order to close the issue.

Saludos
