### ISSUE TITLE
OneTopic Error - Unknown course section in course "XXX"

### ISSUE THREAD

**Issue by markt71** [davidherney/moodle-format_onetopic#45]
We are using Moodle 3.3.4 with a mySQL database and the OneTopic plugin version san juan (2018010602). However, after an the upgrade of Moodle from 3.1.5 to 3.3.4 some course are now displaying the error message, "Unknown course section in course "XXX"" if they are set to the OneTopic format. If we switch the format to Topics the course shows fine.

![onetopic error](https://user-images.githubusercontent.com/38537885/40735482-e55d72c4-6400-11e8-8ef4-295bf54d5f8a.PNG)

I am currently not aware of how the error is being produced, so I cannot list how to replicate it for testing.

Next, I checked and compared some database entries in the course_format_options table for both a course that is showing the error and one that is not.

It appears the courses showing the error have only records for the sectionid 0, and none of the other sections used in the course have records in the table. The courses not showing the error have records for all the sectionids in the course. 

Is there any way to possible resolve the error?

**Comment by drfyzziks** [comment]
I've also just encountered the same issue, on a Moodle 3.5.1 server running Onetopic san juan (2018010604). Unfortunately, I can't provide a copy of our database (it's huge!) but am willing to help out however I can...

Unknown course section in course "HIST 1221_SW3 - Post-Confederation Canadian History (Summer 2017 Belshaw)"

More information about this error

Debug info: 
Error code: unknowncoursesection
Stack trace:
line 482 of /lib/setuplib.php: moodle_exception thrown
line 185 of /course/format/onetopic/renderer.php: call to print_error()
line 93 of /course/format/onetopic/format.php: call to format_onetopic_renderer->print_single_section_page()
line 280 of /course/view.php: call to require()

**Comment by drfyzziks** [comment]
A little more info: unlike markt71, the course_format_options table does contain records for sections beyond section0. Also: the problem still occurs when I backup/restore to a new course container. Switching the course format to any format other than Onetopic results in the error going away and the course content becoming visible.

**Comment by markt71** [comment]
I wanted to let you all know that I have also started a thread about this on Moodle.org, [https://moodle.org/mod/forum/discuss.php?d=371726#p1508642], if anyone needs more information. Thank you.

**Comment by joostvanderborg** [comment]
We have this in one of our installations too, on Moodle 3.5 and 3.5.1. I managed to test locally, and for us the issue appears when:
- the course table has the marker column set to a higher number than there are sections in the course (no idea if this is normal behaviour, but for several courses this is the case, most are set to 0, some have numbers up to 13).
- no section is defined in the request
- the user has nothing set in `$USER->display[coursenum]`

I tested a fix, checking if the course marker is higher than the section count for the course in format.php. I'll try to create a PR for this. Since I'm not certain on the intended use of the marker column, I'm not sure of side effects of this change.

**Comment by davidherney** [comment]
Hi...

I applied the @joostvanderborg's  fix in master branch.

Please, test if it solve the error into the other platforms in order to apply it into the other branches.

Saludos

**Comment by ak4t0sh** [comment]
I've also just encountered the same issue and applied @joostvanderborg patch I can confirm it fix the issue for me (Moodle 3.5+) Thx ! :+1:

**Comment by Jarvil** [comment]
Hello,

We tested and this fix works.

**Comment by andurif** [comment]
Hello,

We had the same issue and this patch also fix it in our platform (Moodle 3.5+). Thanks.

I tested some code to understand this issue before finding this patch... I found "explanations" about the first point raised by @joostvanderborg . If we remove the highlighted section, moodle change the marker column value to the number of sections plus 1 (marker value is now higher than number of sections and error appears). I don't know if it's the wanted behaviour but it can also causes some issue in other course format plugins. To me it seems make more sense to set this marker to 0 in this case. Maybe this can be useful to report this ? (If a new section is created after, the new one will be highlighted).

I have also potential issue when I highlight a hidden section (no idea why do that but it's possible). If we refresh the current course page, we (students) have this message "Sorry, but you do not currently have permissions to do that (View hidden sections)".
Maybe I will try to create a PR to take the course visibility into account.

**Comment by andurif** [comment]
Hello, I created the PR #57 to add some check on the section visibility.
Do not hesitate to test it on the other platforms to see if this is useful.
Regards.

**Comment by davidherney** [comment]
Hi...

I fix it in the **MOODLE_33_select_visible_tab_by_default** branch (Moodle 3.3+, 3.4+ and 3.5+). It is a big change and I need other testers before public it officially. Please, help me testing this branch and send me the comments.

Thx

Saludos

**Comment by Jarvil** [comment]
Hello @davidherney 

I have found that this fix works fine, please add it to the master.

**Comment by davidherney** [comment]
Ready! Version 2018010606.
