### ISSUE TITLE
section_edit_controls() is deprecated, please use section_edit_control_items() instead.

### ISSUE THREAD

**Issue by bmackenty** [davidherney/moodle-format_onetopic#5]
Moodle 3.0.1+ (Build: 20151231) turning on editing using onetopic version 2015051700 produces the following warning. onetopic is working as expected, but this warning is visible: 

section_edit_controls() is deprecated, please use section_edit_control_items() instead.

    line 278 of /course/format/renderer.php: call to debugging()
    line 115 of /course/format/onetopic/renderer.php: call to format_section_renderer_base->section_edit_controls()
    line 613 of /course/format/onetopic/renderer.php: call to format_onetopic_renderer->section_edit_controls()
    line 574 of /course/format/onetopic/renderer.php: call to format_onetopic_renderer->section_right_content()
    line 446 of /course/format/onetopic/renderer.php: call to format_onetopic_renderer->section_header()
    line 89 of /course/format/onetopic/format.php: call to format_onetopic_renderer->print_single_section_page()
    line 280 of /course/view.php: call to require()

thank you for supporting this wonderful product!!

**Comment by AviMoto** [comment]
I send two pull request to solve this issue
https://github.com/davidherney/moodle-format_onetopic/pull/7

**Comment by davidherney** [comment]
You sent a merge, but not created a pull request. However, sbourget user sent other fix before.

Thanks by your interest.

**Comment by AviMoto** [comment]
Hi, 
sbourget just use section_edit_control_items() functions and not add the set active section button, please check it again

**Comment by davidherney** [comment]
Hi...
You are right, however, I added this and other functionalities in last version (2016020501). You can check it, and please send me your comments or report the issues.

thx

Saludos
