### ISSUE TITLE
Feature request: deleted section and activities should go to the bin

### ISSUE THREAD

**Issue by Jarvil** [davidherney/moodle-format_onetopic#53]
Hello,

If you delete a section/tab in Onetopic everything is lost because the plugin doesn't support Moodle recycle bin;

https://docs.moodle.org/35/en/Recycle_bin

Could you make it so that a deleted section and its contents would go the recycle bin instead of instant permanent deletion?

**Comment by sarahjcotton** [comment]
> Hello,
> 
> If you delete a section/tab in Onetopic everything is lost because the plugin doesn't support Moodle recycle bin;
> 
> https://docs.moodle.org/35/en/Recycle_bin
> 
> Could you make it so that a deleted section and its contents would go the recycle bin instead of instant permanent deletion?

We are on 3.5 and deleting sections does indeed put items in the recycle bin however it relies on the cron being run.

**Comment by Jarvil** [comment]
@davidherney

**Comment by davidherney** [comment]
Thanks @sarahjcotton, you have reason, the recycle bin is controlled by moodle core and it is independent of course format.

I proceed to close this old report.

Saludos
