### ISSUE TITLE
Student cannot open course if he/she opens 0 section

### ISSUE THREAD

**Issue by Jarvil** [davidherney/moodle-format_onetopic#55]
Tested with Moodle 3.3 and san juan (2018010604) & san juan (2018010602)

Hello,

I have a course that has multiple tabs which some of are hidden. If as a student I open the course and click the 0 tab (which is shown as a tab) it gives an error: 

**"Sorry, but you do not currently have permissions to do that (View hidden sections)" 
Debug info: 
Error code: nopermissions 
Stack trace: •line 788 of /lib/accesslib.php: required_capability_exception thrown
•line 116 of /course/view.php: call to require_capability()**

And if I click Continue nothing happens.

![error](https://user-images.githubusercontent.com/15193418/47917399-0f7a0500-deb2-11e8-8389-5ea8694cab6a.PNG)

Only when I close the browser and open the course it works again. Also all activities on every tab are hidden from the student even when I have activities visible to students. And lastly If I open any other tab first than the 0 tab the course and tab 0 works normally.

**Comment by Jarvil** [comment]
My bug is allmost excatly like this; 

https://moodle.org/mod/forum/discuss.php?d=260692#

**Comment by Jarvil** [comment]
Hello,

The bug seems to be that if you have Highlighted a hidden topic user will get these errors on the 0-section.

**Comment by davidherney** [comment]
Hi...

It is the same issue than #45. I fix it in the MOODLE_33_select_visible_tab_by_default branch (Moodle 3.3+, 3.4+ and 3.5+). Please, help me testing this branch and send me the comments.

Thx

Saludos
