### ISSUE TITLE
Changing role to student causes error/prevents Moodle usage

### ISSUE THREAD

**Issue by Jarvil** [davidherney/moodle-format_onetopic#58]
Hello,

There is a bug in format_onetopic (san juan
2018010604) tested with Moodle 3.5.3 (Build: 20181112)

When you restrict a whole tab for a spesific group f.ex group1 and change your role to student as an teacher or administrator your browser displays an error **"This page isn’t working http://nnnnn.nnnn redirected you too many times."** and you cannot open Moodle unless you close your browser or clear cookies.

I belive this is because teacher doesn't belong to group 1 and plugin doesn't inherit any rights from the "parent" role (teacher/administrator) when chancing role.

The plugin should display error message f.ex. "you do not belong to group 1 so you cannot see this tab" or something, right now whole Moodle is being "replaced" with this error message and you cannot open Moodle anymore unless you close the whole browser or clear cookies from Moodle.

Steps to repeat:

0. Create group called group1
1. Restrict a tab for group1
2. Open this tab as a teacher or administrator
3. Change your role to student
4. See the problem

![group1](https://user-images.githubusercontent.com/15193418/48901647-c5f05a80-ee5e-11e8-83c6-51208d00fc40.PNG)
![group2](https://user-images.githubusercontent.com/15193418/48901646-c557c400-ee5e-11e8-94b7-2e3b38de1709.PNG)
![group3](https://user-images.githubusercontent.com/15193418/48901645-c557c400-ee5e-11e8-94d5-03b96b982272.png)

**Comment by davidherney** [comment]
Hi @Jarvil ...

This issue is fixed into the **MOODLE_33_select_visible_tab_by_default** branch. Please help me testing and comment me.

Saludos

**Comment by Jarvil** [comment]
Hello @davidherney 

We tested the fix in branch MOODLE_33_select_visible_tab_by_default. 

Teacher has a course that has tab3 restritected to a group1. After that when teacher changes his role to a student (and he doesn't belong to any group) course doesn't give any errors anymore and he can see tab3 as restricted tab and cannot access it.

But when I add teacher to group1 and he changes his role to a student -> tab 3 is still unavailable to him even when he belongs to the group1.

**Comment by davidherney** [comment]
Hi @Jarvil 

Please test again. It work fine to me. I made a new released today.

Saludos
