### ISSUE TITLE
Active tab loses default style when custom colours applied

### ISSUE THREAD

**Issue by hkalant** [davidherney/moodle-format_onetopic#68]
When I have chosen for all tabs to have a specific background and text color (from the section settings), then it's not obvious which tab is the active one.

Steps to reproduce:
1. Go to a course in Moodle with the One Topic format.
3. Turn editing on and edit one section.
4. Choose #424a52 for background colour and #ffffff for text colour and save changes.
5. Repeat step 4 for all sections.
6. Once you save changes, click through each section tab. 

Not obvious which tab is the active one.

Is this something which can be solved by applying CSS in the "CSS properties" field at the bottom of the section settings?

**Comment by davidherney** [comment]
Hi...

the current tab has a specific css class: "active". You can set styles in your theme in order to make a different presentation. For example, change the font-bold or the tab size. It is not a bug, it is a plugin feature.

Do you recommend another behavior to it?

Saludos

**Comment by hkalant** [comment]
Thanks for your answer.

No, I think the behaviour is fine and it's very useful that it has the 'active' class.

However, it's not obvious to me, how I can customise that 'active' class with custom CSS only for a specific course, without having to change the global CSS of the whole theme.

What I'm trying to achieve is to customise the active tab only for one course, not all of our courses in Moodle.

If you can provide advice on this, that would be really helpful.

Many thanks,
Harry

**Comment by davidherney** [comment]
Hi @hkalant...
I am sorry but there is not way to custom it for a single course.

Saludos

**Comment by hkalant** [comment]
Hi @davidherney 

No problem, feel free to close this.

But be aware of that: since you allow users to add text and color background to the tabs, if it's not obvious which tab is the 'active', since a user might choose the same color for all tabs, then that's a bug.

Because when users choose custom settings, which is something you allowed them to do in the first place, and that causes the course format to produce an incorrect or unexpected result (which is it doesn't highlight the 'active' tab in any way), then that's a definition of a software bug.

You might want to consider adding options like in the example below in future versions of the format:

![one-topic-more-options](https://user-images.githubusercontent.com/2014422/57024954-c53dca80-6c2d-11e9-8ea3-1d5fe2674635.png)

Best wishes,
Harry
