### ISSUE TITLE
Moodle 3.7 and 3.8 official compatibility

### ISSUE THREAD

**Issue by kinnectus** [davidherney/moodle-format_onetopic#71]
We currently use Moodle 3.6 and can see that there is official confirmation through the Moodle plugin catalogue that this course format is compatible up to 3.6.

Please can the plugin be tested and the Moodle catalogue be updated to provide confirmation of support for 3.7 and 3.8?

We are a University and are trying to stick to a policy that we only use plugins that have, amongst other things, forward compatibility of Moodle versions ahead of our current production environment. We review plugins for removal where future compatibility may be problematic if the author has not confirmed compatibility.

**Comment by davidherney** [comment]
It is ready.
