### ISSUE TITLE
Announcements forum

### ISSUE THREAD

**Issue by cmadland** [davidherney/moodle-format_onetopic#73]
Seems that OneTopic format blocks creation of an Announcements forum when a new course is created. Am I missing something?

**Comment by davidherney** [comment]
Hi @cmadland ...

The Onetopic format don't block the creation of the forum. It process is managed by moodle's core in the new versions.
I checked it and the forum is created normally when I create a new course.

What Moodle version you use?

Saludos

**Comment by cmadland** [comment]
Interesting. We are using 3.5.

When I create a new course with OneTopic as the format, the Announcement forum does not show on the Index tab. When I switch to a different format, it does. Could it be hidden somewhere? Moodle is clearly creating it and showing with different formats.

Thanks.
________________________________

**Comment by davidherney** [comment]
I checked in moodle 3.5+ and it work fine with Onetopic format, the Announcement forum is added into Section 0. Maybe is something in your platform or maybe you used the incorrect Onetopic version.... check it.

Saludos

**Comment by cmadland** [comment]
Looks like an update fixes the issue. Thank you
