### ISSUE TITLE
Latest version in git repository is not the latest version

### ISSUE THREAD

**Issue by markidm** [davidherney/moodle-format_onetopic#74]
This isn't exactly an 'issue', but I use docker to build my Moodle server, and I fetch the latest version of plugins via their git repositories. I notice that the latest version in this repository is one release behind the version in the Moodle plugins directory - is there any chance you can commit version 2018010608 to this repository?

**Comment by davidherney** [comment]
Ready!!

**Comment by markidm** [comment]
Great, thank you!
