### ISSUE TITLE
Adding a permalink system

### ISSUE THREAD

**Issue by fxpar** [davidherney/moodle-format_onetopic#77]
Hi,

SUMMARY
If a new section is created and is moved as sub section of a section, all the following sections are renumbered. The previously made links are not targeting the right section anymore.

FAILED SOLUTION
In normal course format it is possible to use manually created anchors in the page... But they don't work here because Onetopic needs the section number in the url.

Best regards

**Comment by james-cnz** [comment]
Hi fxpar,

Moodle does actually have permanent links for sections that you can use.  These won't work in a copy of a course though.  If you turn editing on and click on the section Edit menu, then hover over the Edit section entry, you should see a URL of the form:
WEBSITE/course/editsection.php?id=SECTION_ID&sr=SECTION_NUMBER
You should get a permanent link if you take the SECTION_ID and put this into a URL of the form:
WEBSITE/course/view.php?id=COURSE_ID&sectionid=SECTION_ID

**Comment by fxpar** [comment]
Hi @james-cnz 
Indeed, this works perfectly!
Thank you very much (I will link to your answer in the [moodle onetopic plugin](https://moodle.org/plugins/format_onetopic) page) !
Cheers
François

**Comment by james-cnz** [comment]
Hi @fxpar,

Just be aware that if you use permanent section links within a course, these won't work in a copy of the course.  e.g. If you make a backup of a course, and restore the backup as a new course, any permanent section links within the copy will have their course IDs updated for the new course, but won't have their section IDs updated, so trying to follow the link, Moodle will look for the old section in the new course, and won't find it, returning an error.

Also, for anyone using an older version of Onetopic, I just noticed that although support for this feature is included in the current version, san juan 2018010608, it doesn't seem to be included in san juan 2018010604, so you may need to upgrade to use it.
