### ISSUE TITLE
Moodle 3.9 support?

### ISSUE THREAD

**Issue by Urpokarhu1** [davidherney/moodle-format_onetopic#82]
Hello,

will this plugin support Moodle 3.9?

**Comment by Urpokarhu1** [comment]
@davidherney

**Comment by Urpokarhu1** [comment]
@davidherney any news on 3.9 version?

**Comment by davidherney** [comment]
It is supported in current master, 905e879bbf0339cf593b2b298f1dc489fe2fb490 commit.
