### ISSUE TITLE
Child tabs should inherit "hidden from students" from parent tab

### ISSUE THREAD

**Issue by nataliakurikova** [davidherney/moodle-format_onetopic#83]
Hello,

We use Onetopic format with parent and child sections.
When we hide a parent section from students, we expect that its child tabs become hidden as well.
This is, however, not true: if a parent section is hidden, the students see its child tabs as child tabs of the previous parent section.

As a workaround, we are hiding each of the tabs in a nest: the parent tab and all its child tabs. But it can be very easy to overlook this and inadvertently leave child tabs available to students.

Are there any plans to fix this? Thank you.

**Comment by davidherney** [comment]
Solved in  #107

Saludos
