### ISSUE TITLE
import into section - makes error

### ISSUE THREAD

**Issue by neeesn** [davidherney/moodle-format_onetopic#84]
We have a problem with onetopic, when we import a section we get errors.
Moodle is version 3.8.4 and classic theme
![onetopic-error](https://user-images.githubusercontent.com/1931926/90235341-6f406680-de21-11ea-9d4a-4d30c10e61d9.png)
- First line - "Fejl ved skrivning til database" is danish for "Error writing to Database"

**Comment by davidherney** [comment]
Hi @neeesn 

I've done tests and can't reproduce the error. Have you checked if subsequent releases of Moodle 3.8 show the same error? Please send me the configurations of the source course and the target course to check if it is something of that configuration that causes the error. Do both courses have the onetopic format? Could you give me a copy of the source course / section to test specifically with that information to see if I reproduce the error?

Saludos

**Comment by neeesn** [comment]
We have updated to Moodle version 3.9.3 and it seems the error has corrected its self.
