### ISSUE TITLE
Fatal error on 3.9 upgrade 

### ISSUE THREAD

**Issue by mnods** [davidherney/moodle-format_onetopic#85]
Hi, debugging:

Warning: require_once(.... /course/format/topics/db/upgradelib.php): failed to open stream: No such file or directory in .... /course/format/onetopic/db/upgradelib.php on line 27

Fatal error: require_once(): Failed opening required '.... /course/format/topics/db/upgradelib.php' (include_path='.... lib/pear:.:/usr/share/php') in .... /course/format/onetopic/db/upgradelib.php on line 27

only thing i've done is comment out that line to get it to install on a dev environment, not sure if more needs doing so hopefully you can have a look sometime to check.

Cheers

**Comment by davidscotson** [comment]
I hit this too.

The core change that removed the file was

https://github.com/moodle/moodle/commit/3f224a1a4115665ac5a1fc469a7ac03422ed287c

And so just removing it should be fine for newer upgrades I think, but older versions upgrading will still need it possibly.

**Comment by tonyjbutler** [comment]
+1

**Comment by drfyzziks** [comment]
+1 here

Upgrading from one LTS version (3.5.13) to 3.9.1 when we ran into this.

**Comment by t-schroeder** [comment]
I ran into this as well. My fix consists of just copying the function that got removed from Moodle into this plugin.

**Comment by golenkovm** [comment]
Hey @t-schroeder 

As I can see there is only one scenario when this code could be called.
When someone is running moodle 3.9 with very very old `format_onetopic` plugin installed (2016071402 version, which was before Moodle 3.3). See this commit: https://github.com/davidherney/moodle-format_onetopic/commit/9a4640c590a6302beb833feda849f85d47a52797
But this version of the plugin is not compatible with Moodle 3.3 and therefore with Moodle 3.9. Which means this function will never be called in Moodle 3.9.
So I think it would be enough just to check if the file exists. See my PR #88 

Hey @davidherney could you please have a look at this issue? Appreciate it.

Cheer,
Mikhail

**Comment by t-schroeder** [comment]
Hi @golenkovm 

what happens if someone were to upgrade Moodle itself together with this plugin from something <= 3.2 to 3.9? Moodle would try to perform that upgrade step and would fail with your solution because of an undefined function `format_topics_upgrade_hide_extra_sections`.

I get that this version of the plugin is not compatible with Moodle versions < 3.3 but Moodle would still perform the upgrade steps if you upgrade from a sufficiently old version of the plugin.


Cheers,
Tim

**Comment by golenkovm** [comment]
Hi Tim,

That looks to be a big jump 31=>39.
Have you tested this scenario?

Cheers,
Mikhail

**Comment by tonyjbutler** [comment]
I encountered this when upgrading from 3.5 to 3.9 with the new plugin code in place.

**Comment by t-schroeder** [comment]
Hi Mikhail,

yeah it is a big jump. But there are people still using old Moodle versions. See the graph at the bottom of https://stats.moodle.org/ and these are probably just the sites registered with Moodle. Why not be on the safe side and still support upgrades from these old versions?

I haven't yet tested this yet. It's a bit involved since Moodle 3.1 requires another PHP version than 3.9.

Cheers,
Tim

**Comment by drfyzziks** [comment]
> yeah it is a big jump. But there are people still using old Moodle versions. See the graph at the bottom of https://stats.moodle.org/ and these are just the sites registered with Moodle.

Agreed. Oftentimes larger institutions like to go from one Long Term Support release to another - especially if some of their plugins (like student information systems integrations) aren't updated with every Moodle point release. Moodle 3.5.14 just came out a couple weeks ago, and 3.5 gets security support out until May 2021.

**Comment by t-schroeder** [comment]
I found out you can't upgrade directly from Moodle < 3.5 to 3.9. See https://github.com/moodle/moodle/blob/e049d30613b4ef09910b1b89ae97f176bdc122cc/admin/environment.xml#L2985

That changes things. So if someone were to upgrade from a very old version they'd need to do it in steps. In that case I'm closing my pull request and vote for @golenkovm's solution. It will make sure the upgrade step is performed when going from e.g. 3.1 to 3.5 while fixing the error that occurs when going from 3.5 to 3.9.

**Comment by MathieuDomingo** [comment]
Just got this issue going from 3.5 to 3.9
golenkovm's solution is perfect , update can go after this plugin :+1:

**Comment by davidherney** [comment]
Hi all..

According to the Moodle guidelines I have removed the update validation. The Onetopic version for Moodle 3.9 should
be upgraded from a Moodle version 3.5 or higher.

Thank you for your comments.

Saludos
