### ISSUE TITLE
Feature Request: Bulk move items between tabs

### ISSUE THREAD

**Issue by lassnj** [davidherney/moodle-format_onetopic#86]
it would be nice if you could move several items (activities and materials) between tabs at once.

**Comment by davidherney** [comment]
Hi @lassnj ...

You can do it. Yo can use the section 0 as a bridge (if it is before the tabs) or you can disable the asynchronous actions with the "Asynchronous edit actions" option (page bottom in course edition mode).

Maybe i could add a faster option latter but i don't have time in this moment.

Saludos
