### ISSUE TITLE
Coding error detected (Moodle 3.9.1+)

### ISSUE THREAD

**Issue by chiaravicere** [davidherney/moodle-format_onetopic#89]
Hello, I installed the plugin on Moodle 3.9.1+ (Build: 20200822). When I enter a new course with Onetopic format and I turn edition mode on, this is the error (wich prevents me doing anything):

**Coding error detected, it must be fixed by a programmer: section_edit_controls() can not be used anymore. Please use section_edit_control_items() instead.**

**Comment by golenkovm** [comment]
Hi @chiaravicere 

I couldn't replicate the issue you mentioned.
Is the plugin that you use has the latest code?
Could you please post the full trace of the error?

Cheers,
Mikhail

**Comment by chiaravicere** [comment]
Thank you for your fast reply. I uninstalled and re-installed being sure that it was the latest version, now the error is disappeared. Thanks.
