### ISSUE TITLE
Feature request: in the settings page the option to choose YES/NO for section zero as tab

### ISSUE THREAD

**Issue by gjtielemans** [davidherney/moodle-format_onetopic#93]
When you copy a set of courses from last year or so, you can inherit course format oneTopic but not the settings like the one to choose to show section zero as a tab.
Is it possible to create a settings page for that?

**Comment by davidherney** [comment]
Hi @gjtielemans ...

Do you use the Upload courses feature to copy them?

Because it have a issue related: https://tracker.moodle.org/browse/MDL-50913

It's not controlled by course format.

Let me know more about your idea

Saludos
