### ISSUE TITLE
font color does not change on tabs

### ISSUE THREAD

**Issue by rudy500** [davidherney/moodle-format_onetopic#99]
when changing the color of the fonts (text) of the tabs, this is not applied, this was checked in the chrome / firefox browser in developer mode and indicates an error when trying to apply the style
![example error1](https://user-images.githubusercontent.com/49110698/111189536-f1019980-8594-11eb-9145-d57c59152a3e.jpg)
![example error2](https://user-images.githubusercontent.com/49110698/111189537-f19a3000-8594-11eb-9b60-87509cb02c40.jpg)
![example error3](https://user-images.githubusercontent.com/49110698/111189538-f232c680-8594-11eb-8f0f-700f16bb1449.jpg)
![example error4](https://user-images.githubusercontent.com/49110698/111189541-f232c680-8594-11eb-9241-f5a663c5516a.jpg)

**Comment by davidherney** [comment]
The color changes in default themes:
![imagen](https://user-images.githubusercontent.com/6455806/143608238-44b159df-fd05-4767-84a7-cde7fbbe6eac.png)

But, some themes like "adaptable" overwrite it with "important" sentence. It is a theme not format decision.
![imagen](https://user-images.githubusercontent.com/6455806/143608397-b5b1696f-3bd1-4b4c-af85-2fee6b298591.png)

Saludos

**Comment by gjb2048** [comment]
Now being addressed in Adaptable, please see: https://gitlab.com/jezhops/moodle-theme_adaptable/-/issues/264.
